# Generated by Django 5.1.2 on 2024-11-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Age', models.IntegerField(default='')),
                ('Qualification', models.CharField(default='', max_length=50)),
                ('Address', models.CharField(default='', max_length=50)),
                ('PhoneNo', models.IntegerField(default='')),
                ('Email', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
